language: python

install:
    - pip install -U platformio
    - pio lib install "Servo"

script:
    - git checkout release/madgrizzle
    - platformio run -e megaatmega2560
    - mv .pio/build/megaatmega2560/firmware.hex ./madgrizzle-$(sed -n -e 's/^.*VERSIONNUMBER //p' cnc_ctrl_v1/Maslow.h).hex
    - git checkout release/maslowcnc
    - platformio run -e megaatmega2560
    - mv .pio/build/megaatmega2560/firmware.hex ./maslowcnc-$(sed -n -e 's/^.*VERSIONNUMBER //p' cnc_ctrl_v1/Maslow.h).hex
    - git checkout release/holey
    - platformio run -e megaatmega2560
    - mv .pio/build/megaatmega2560/firmware.hex ./holey-$(sed -n -e 's/^.*VERSIONNUMBER //p' cnc_ctrl_v1/Maslow.h).hex
    - ls -la
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: *.hex
  skip_cleanup: true
  draft: true
  on:
    tags: true
