language: python

install:
    - pip install -U platformio
    - pio lib install "Servo"

script:
    - pio run -e megaatmega2560
    - mv .pio/build/megaatmega2560/firmware.hex ./madgrizzle-$(sed -n -e 's/^.*VERSIONNUMBER //p' cnc_ctrl_v1/Maslow.h).hex
    - ls -l
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: *.hex
  skip_cleanup: true
  draft: true
  on:
    tags: true
    
